version: '3.4'
services:
  app:
    container_name: autofilter_server
    build:
      context: .
    volumes:
      - .:/home/autofilter_server
    command: uvicorn runserver:app --host 0.0.0.0 --port 8000
    network_mode: "host"