version: '3.4'
services:
  app:
    container_name: autofilter
    build:
      context: .
    volumes:
      - .:/home/autofilter
    command: uvicorn autofilter.adapters.create_app:app --host 0.0.0.0 --port 9600
    network_mode: "host"